[application]

[web.app]

# HTML title tag content
title = "gitpro"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.nichehlikes15.gitpro"
name = "GitPro"
version = "0.1.0"
publisher = "nichehlikes15"

[bundle.desktop]
icon = "assets/icons/gitpro.ico"